routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*Route::get('/users',[App\Http\Controllers\UserController::class, 'index'])->name('users.index');

Route::get('/users/{user}/edit',[App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');

Route::put('/users/{user}', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');

Route::delete('/users/{user}',[App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroy');*/

Route::resource('users', App\Http\Controllers\UserController::class)->middleware('admin')->except(['show']);

Route::get('users/{user}', [App\Http\Controllers\UserController::class, 'show'])->name('users.show')->middleware('auth');

Route::resource('cursos', App\Http\Controllers\CursoController::class);

app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    use HasFactory;

     protected $guarded = [];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Curso;

class CursoController extends Controller
{
   
     
    public function index()
    {
        $cursos = Curso::all();

        return view('cursos.index', compact('cursos'));
    }

   
    public function create()
    {
        return view('cursos.create');
    }


    public function store(Request $request)
    {
        

        $curso = Curso::create($request->all());

        return redirect()->route('cursos.index')->with('success', 'Curso añadido a la lista.');
    }

   
    public function show($id)
    {
        $curso = curso::find($id);

        return view('cursos.show', compact('curso'));
    }

   
    public function edit($id)
    {
         $curso = Curso::find($id);
         return view('cursos.edit', compact('curso'));
    }

    
    public function update(Request $request, Curso $curso)
    {
        
        $curso->update($request->all());

        /*$curso->name = $request->name;
        $curso->descripcion = $request->descripcion;
        $curso->categoria = $request->categoria;
        
        $curso->save();*/

        return redirect()->route('cursos.index')->with('success', 'Curso actualizado');
    }

    
    public function destroy($id)
    {
        $curso = Curso::find($id)->delete();

        return redirect()->route('cursos.index')->with('success', 'Curso eliminado');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{

    public function index()
    {
        $users = User::all();

        return view('user.index', compact ('users'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        $user = User::find($id);

        return view('user.show', compact('user'));
    }

    public function edit($id)
    {
        $user = User::find($id);
         return view('user.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;

        $user->save();

        return redirect()->route('users.index')->with('success', 'Usuario actualizado');
    }

    public function destroy($id)
    {
         $user = User::find($id)->delete();

        return redirect()->route('users.index')->with('success', 'Usuario eliminado');
        
    }
}

resources/views/cursos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><strong>Cursos</strong>

                 <form action="{{route('cursos.store')}}" method="post">
                    @csrf
                  <div class="mb-3">
                    <label for="name" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="name" name="name">
                    
                </div>
                <div class="mb-3">
                    <label for="descripcion" class="form-label">Descrición</label>
                    <input type="text" class="form-control" id="descripcion" name="descripcion">
                </div>

                <div class="mb-3">
                    <label for="categoria" class="form-label">categoria</label>
                    <input type="text" class="form-control" id="categoria" name="categoria">
                </div>

                <button type="submit" class="btn btn-primary">Crear</button>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cursos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><strong>Cursos</strong>

                 <form action="{{route('cursos.update', $curso->id)}}" method="post">
                    @csrf
                    @method('put')
                  <div class="mb-3">
                    <label for="name" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="name" name="name">
                    
                </div>
                <div class="mb-3">
                    <label for="descripcion" class="form-label">Descrición</label>
                    <input type="text" class="form-control" id="descripcion" name="descripcion">
                </div>

                <div class="mb-3">
                    <label for="categoria" class="form-label">categoria</label>
                    <input type="text" class="form-control" id="categoria" name="categoria">
                </div>

                <button type="submit" class="btn btn-primary">Actualizar</button>
            </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cursos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><strong>Cursos</strong>

                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                			<div class="float-right">
                                <a href="{{route('cursos.create')}}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Añadir Curso nuevo') }}
                                </a>
                            </div>
                    
                </div>

                <div class="card-body shadow px-3">
   					<table class="table">
   						<caption>Lista de cursos</caption>
					  <thead>
					    <tr>
					      <th scope="col">ID</th>	
					      <th scope="col">Curso</th>
					      <th scope="col">Categoria</th>
					    </tr>
					  </thead>
					<tbody>
                    @foreach($cursos as $curso)
                        <tr>
                          <td>{{$curso->id}}</td>
                          <td>{{$curso->name}}</td>
                          <td>{{$curso->categoria}}</td>
                          
                          <td>
                            <form action="{{ route('cursos.destroy', $curso->id )}}" method="POST">
                                <a class="btn btn-sm btn-primary " href="{{route('cursos.show', $curso->id)}}"><i class="fa fa-fw fa-eye"></i> Ver</a>
                                <a class="btn btn-sm btn-primary " href="{{route('cursos.edit', $curso->id)}}"><i class="fa fa-fw fa-eye"></i> Actualizar</a>
                                @csrf
                                @method('DELETE')
                                <button type ="submit" class="btn btn-outline-danger btn-sm">Eliminar</button>
                            </form>
                        </td>
                        </tr>

                    @endforeach
                      </tbody>

					</table>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cursos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title h5">{{ $curso->name }}</span>
                        </div>
                        
                    </div>

                    <div class="card-body">
                        
                        <div class="float-end">
                            <a class="btn btn-primary btn-sm" href="{{ route('cursos.index') }}"> Regresar</a>
                        </div>

                        <div>
                            <strong>Nombre del curso:</strong>
                            {{ $curso->name }}
                        </div>

                       

                        <div class="form-group">
                            <strong>Descripción:</strong>
                            {{ $curso->descripcion }}
                        </div>


                        <div class="form-group">
                            <strong>Categoria:</strong>
                            {{ $curso->categoria }}
                        </div>

                        
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Inicio</div> <!-- Parte del header del cuadro -->

                <!-- Esto es un mensaje que se muestra-->
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Estas logeado
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @if(Auth::check())
                    @if(Auth::user()->role == 'Admin')
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('users.index')}}">Usuario</a>
                        </li>
                    </ul>
                    @endif
                    
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('cursos.index')}}">Cursos</a>
                        </li>
                    </ul>
                    
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('users.show', auth()->id())}}">Perfil</a>
                        </li>
                    </ul>
                    
                    @endif

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">Inicia</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">Registrate</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Salir</a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Actualizar</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('users.update', $user->id) }}">
                        @csrf
                        @method ('put') 
                        <div class="row mb-3">
                            <label for="name" class="col-md-4 col-form-label text-md-end">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="email" class="col-md-4 col-form-label text-md-end">Correo electronico</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                      

                        <div class="row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Actualizar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Usuarios

                	@if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    
                </div>

                <div class="card-body shadow px-3">
   					<table class="table">
   						<caption>Lista de usuarios</caption>
					  <thead>
					    <tr>
					      <th scope="col">ID</th>	
					      <th scope="col">Usuario</th>
					      <th scope="col">Correo</th>
					    </tr>
					  </thead>
					  <tbody>
					@foreach($users as $user)
					    <tr>
					      <td>{{$user->id}}</td>
					      <td>{{$user->name}}</td>
					      <td>{{$user->email}}</td>
					      
					      <td>
					      	<form action="{{ route('users.destroy', $user->id )}}" method="POST">
					      		<a class="btn btn-sm btn-primary " href="{{route('users.show', $user->id)}}"><i class="fa fa-fw fa-eye"></i> Ver</a>
					      		<a class="btn btn-sm btn-primary " href="{{route('users.edit', $user->id)}}"><i class="fa fa-fw fa-eye"></i> Actualizar</a>
						    	@csrf
						    	@method('DELETE')
						    	<button type ="submit" class="btn btn-outline-danger btn-sm">Eliminar</button>
					    	</form>
						</td>
					    </tr>

					@endforeach
					  </tbody>
					</table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title h5">{{ $user->name }}</span>
                        </div>
                        
                    </div>

                    <div class="card-body">
                        
                        <div class="float-end">
                            <a class="btn btn-primary btn-sm" href="{{ route('users.index') }}"> Regresar</a>
                        </div>

                        <div>
                            <strong>Nombre de Usuario:</strong>
                            {{ $user->name }}
                        </div>

                       

                        <div class="form-group">
                            <strong>Correo Electrónico:</strong>
                            {{ $user->email }}
                        </div>

                        <div class="form-group">
                            <strong>Rol:</strong>
                            {{ $user->role }}
                        </div>

                        
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection